name: yapi_api
description: A Dart package for interacting with YApi server APIs. Provides easy-to-use methods to fetch interface and project data from YApi with proper authentication and error handling.
version: 1.0.1
repository: https://github.com/fluttercandies/yapi_api

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  http: ^1.5.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
